version: '2'
services:
  laos-databreach:
    image: mysql:8.0
    container_name: laos-databreach
    command: --default-authentication-plugin=mysql_native_password
#        working_dir: /application
    volumes:
      - .:/application
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Greyabuabu!123
      - MYSQL_DATABASE=databreach
      - MYSQL_USER=db_databreach
      - MYSQL_PASSWORD=Greyabuabu!
    ports:
      - "3307:3307"
  laos-databreach-web:
    container_name: laos-databreach-web
    build:
      context: ./
    volumes:
      - ./src/*:/var/www/html/*
    ports:
      - "16005:80"
    depends_on:
      - laos-databreach