version: '3'
services:
  laosarena:
    container_name: pwn2
    restart: always
    build:
      context: .
    working_dir: /home/ctf
    ports:
      - "17004:31337" # exposed:local
    entrypoint: /etc/run_xinetd.sh
    read_only: true
