version: '3'
services:
  laosarena:
    container_name: babypwn
    restart: always
    build:
      context: .
    working_dir: /home/ctf
    ports:
      - "17001:31337" # exposed:local
    entrypoint: /etc/run_xinetd.sh
    read_only: true
