version: '3'
services:
  laosarena:
    container_name: hackthis
    restart: always
    build:
      context: .
      args:
        binary: chall.py
    ports:
      - "17001:5000" # exposed:local
    read_only: true
